{% set name = "suitcase-utils" %}
{% set version = "0.5.4" %}
{% set sha256 = "5c3fee0896d1ebf89d1a7b41198a14a09866065c62fe17adbb1cf1c15d636d89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - suitcase.utils

about:
  home: https://blueskyproject.io/suitcase
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility functions and test fixtures for suitcase-* packages
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-utils
